name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version (ex: 3.1.1)"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Build phar
        run: php -d phar.readonly=0 build.php

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: v${{ github.event.inputs.version }}
          files: EasyEdit.phar
          generate_release_notes: true
